export const SOFT_TOOL_ERROR_CODES = [
  "POLICY_BLOCKED",
  "CONFIRMATION_REQUIRED",
  "CONFIRMATION_DENIED",
  "ACCESS_DENIED",
  "COMMAND_BLOCKED",
  "TOOL_NOT_FOUND",
  "INVALID_ARGUMENTS",
  "READ_ONLY",
  "TOOL_DISABLED",
  "NETWORK_DENIED",
  "TERMINAL_SANDBOX_UNAVAILABLE",
  "PATH_UNTRUSTED",
  "PATH_DENIED",
  "PATH_PROTECTED",
  "BUDGET_EXCEEDED",
  "PROFILE_LOCKED",
  "NOT_FOUND",
  "PLUGIN_DENIED",
] as const;

const SOFT_TOOL_ERROR_CODE_SET = new Set<string>(SOFT_TOOL_ERROR_CODES);

export function isSoftToolErrorCode(code: string): boolean {
  return SOFT_TOOL_ERROR_CODE_SET.has(code);
}
