import { spawn, spawnSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  openSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { homedir, platform } from "node:os";
import { dirname, join } from "node:path";
import {
  configExists,
  getBinWrapperPath,
  getConfigDir,
  getDaemonEntry,
  getLogPath,
  getLogsDir,
  getPidPath,
  getRepoRoot,
  loadConfig,
} from "./config.js";

// ---------------------------------------------------------------------------
// Shell helpers (shared by setup/deploy/device)
// ---------------------------------------------------------------------------

export interface RunResult {
  code: number;
  stdout: string;
  stderr: string;
}

/** Run a command, streaming output to the parent stdio. Throws on failure. */
export function run(
  command: string,
  args: string[],
  options: { cwd?: string; env?: NodeJS.ProcessEnv } = {},
): void {
  const result = spawnSync(command, args, {
    stdio: "inherit",
    cwd: options.cwd,
    env: options.env ?? process.env,
    shell: false,
  });
  if (result.error) {
    throw new Error(`Failed to run \`${command}\`: ${result.error.message}`);
  }
  if (typeof result.status === "number" && result.status !== 0) {
    throw new Error(`\`${command} ${args.join(" ")}\` exited with code ${result.status}`);
  }
}

/** Run a command and capture stdout/stderr without throwing. */
export function runCapture(
  command: string,
  args: string[],
  options: { cwd?: string; env?: NodeJS.ProcessEnv } = {},
): RunResult {
  const result = spawnSync(command, args, {
    encoding: "utf8",
    cwd: options.cwd,
    env: options.env ?? process.env,
    shell: false,
  });
  if (result.error) {
    return { code: 1, stdout: "", stderr: result.error.message };
  }
  return {
    code: typeof result.status === "number" ? result.status : 1,
    stdout: result.stdout ?? "",
    stderr: result.stderr ?? "",
  };
}

/** True if an executable is resolvable on PATH. */
export function commandExists(command: string): boolean {
  const probe = platform() === "win32" ? "where" : "which";
  return runCapture(probe, [command]).code === 0;
}

// ---------------------------------------------------------------------------
// Platform + service metadata
// ---------------------------------------------------------------------------

export type ServiceKind = "launchd" | "systemd" | "none";

export function serviceKind(): ServiceKind {
  const p = platform();
  if (p === "darwin") return "launchd";
  if (p === "linux") return "systemd";
  return "none";
}

const LAUNCHD_LABEL = "com.deckagent.daemon";
const SYSTEMD_UNIT = "deckagent";

function launchAgentPath(home: string = homedir()): string {
  return join(home, "Library", "LaunchAgents", `${LAUNCHD_LABEL}.plist`);
}

function systemdUnitPath(home: string = homedir()): string {
  return join(home, ".config", "systemd", "user", `${SYSTEMD_UNIT}.service`);
}

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

/** Build the daemon (and mcp-server dependency) if the entry is missing. */
export function buildDaemon(repoRoot: string = getRepoRoot(), force = false): void {
  const entry = getDaemonEntry(repoRoot);
  if (existsSync(entry) && !force) return;
  console.log("Building daemon (@deckagent/mcp-server, @deckagent/desktop-daemon)...");
  run(
    "npm",
    ["run", "build", "-w", "@deckagent/mcp-server", "-w", "@deckagent/desktop-daemon"],
    { cwd: repoRoot },
  );
}

// ---------------------------------------------------------------------------
// Wrapper script
// ---------------------------------------------------------------------------

/** Write a fallback wrapper script that launches the daemon directly. */
export function writeWrapperScript(home: string = homedir()): string {
  const wrapper = getBinWrapperPath(home);
  const entry = getDaemonEntry();
  const nodePath = process.execPath;
  mkdirSync(dirname(wrapper), { recursive: true });
  const script = `#!/usr/bin/env bash
# Auto-generated by deckagent. Runs the desktop daemon in the foreground.
exec "${nodePath}" "${entry}"
`;
  writeFileSync(wrapper, script, { mode: 0o755 });
  return wrapper;
}

// ---------------------------------------------------------------------------
// Service install / uninstall
// ---------------------------------------------------------------------------

export function installService(home: string = homedir()): void {
  const kind = serviceKind();
  writeWrapperScript(home);
  mkdirSync(getLogsDir(home), { recursive: true });

  if (kind === "launchd") {
    installLaunchAgent(home);
  } else if (kind === "systemd") {
    installSystemdUnit(home);
  } else {
    console.log(
      "No supported service manager detected. The daemon can still be run with `deckagent daemon start` (background) or `deckagent daemon --foreground`.",
    );
  }
}

function installLaunchAgent(home: string): void {
  const entry = getDaemonEntry();
  const nodePath = process.execPath;
  const outLog = getLogPath(home);
  const errLog = join(getLogsDir(home), "deckagent.error.log");
  const plistPath = launchAgentPath(home);
  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${nodePath}</string>
    <string>${entry}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${outLog}</string>
  <key>StandardErrorPath</key>
  <string>${errLog}</string>
  <key>WorkingDirectory</key>
  <string>${getRepoRoot()}</string>
</dict>
</plist>
`;
  mkdirSync(dirname(plistPath), { recursive: true });
  writeFileSync(plistPath, plist, "utf8");
  // Reload if already loaded, then load.
  runCapture("launchctl", ["unload", plistPath]);
  run("launchctl", ["load", "-w", plistPath]);
  console.log(`Installed LaunchAgent at ${plistPath}`);
}

function installSystemdUnit(home: string): void {
  const entry = getDaemonEntry();
  const nodePath = process.execPath;
  const unitPath = systemdUnitPath(home);
  const unit = `[Unit]
Description=DeckAgent desktop daemon
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${nodePath} ${entry}
WorkingDirectory=${getRepoRoot()}
Restart=on-failure
RestartSec=5
Environment=NODE_ENV=production

[Install]
WantedBy=default.target
`;
  mkdirSync(dirname(unitPath), { recursive: true });
  writeFileSync(unitPath, unit, "utf8");
  run("systemctl", ["--user", "daemon-reload"]);
  run("systemctl", ["--user", "enable", "--now", SYSTEMD_UNIT]);
  console.log(`Installed systemd user unit at ${unitPath}`);
}

export function uninstallService(home: string = homedir()): void {
  const kind = serviceKind();
  if (kind === "launchd") {
    const plistPath = launchAgentPath(home);
    if (existsSync(plistPath)) {
      runCapture("launchctl", ["unload", "-w", plistPath]);
      rmSync(plistPath, { force: true });
      console.log(`Removed LaunchAgent ${plistPath}`);
    }
  } else if (kind === "systemd") {
    const unitPath = systemdUnitPath(home);
    if (existsSync(unitPath)) {
      runCapture("systemctl", ["--user", "disable", "--now", SYSTEMD_UNIT]);
      rmSync(unitPath, { force: true });
      runCapture("systemctl", ["--user", "daemon-reload"]);
      console.log(`Removed systemd user unit ${unitPath}`);
    }
  }
}

// ---------------------------------------------------------------------------
// Service state detection
// ---------------------------------------------------------------------------

export function isServiceInstalled(home: string = homedir()): boolean {
  const kind = serviceKind();
  if (kind === "launchd") return existsSync(launchAgentPath(home));
  if (kind === "systemd") return existsSync(systemdUnitPath(home));
  return false;
}

function isServiceRunning(home: string = homedir()): boolean {
  const kind = serviceKind();
  if (kind === "launchd") {
    const out = runCapture("launchctl", ["list"]);
    return out.code === 0 && out.stdout.includes(LAUNCHD_LABEL);
  }
  if (kind === "systemd") {
    const out = runCapture("systemctl", ["--user", "is-active", SYSTEMD_UNIT]);
    return out.stdout.trim() === "active";
  }
  return false;
}

// ---------------------------------------------------------------------------
// PID-based (fallback) lifecycle
// ---------------------------------------------------------------------------

function readPid(home: string = homedir()): number | null {
  const path = getPidPath(home);
  if (!existsSync(path)) return null;
  const pid = Number.parseInt(readFileSync(path, "utf8").trim(), 10);
  return Number.isFinite(pid) ? pid : null;
}

function pidAlive(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch (err) {
    return (err as NodeJS.ErrnoException).code === "EPERM";
  }
}

function startBackgroundProcess(home: string = homedir()): number {
  const entry = getDaemonEntry();
  mkdirSync(getLogsDir(home), { recursive: true });
  const out = openSync(getLogPath(home), "a");
  const err = openSync(join(getLogsDir(home), "deckagent.error.log"), "a");
  const child = spawn(process.execPath, [entry], {
    cwd: getRepoRoot(),
    detached: true,
    stdio: ["ignore", out, err],
  });
  child.unref();
  const pid = child.pid;
  if (!pid) throw new Error("Failed to start daemon: no PID returned.");
  writeFileSync(getPidPath(home), String(pid), "utf8");
  return pid;
}

// ---------------------------------------------------------------------------
// Public lifecycle commands
// ---------------------------------------------------------------------------

function requireConfig(home: string): void {
  if (!configExists(home)) {
    console.error("No config found. Run `deckagent setup` first.");
    process.exit(1);
  }
}

export function startDaemon(home: string = homedir()): void {
  requireConfig(home);
  buildDaemon();
  if (isServiceInstalled(home)) {
    const kind = serviceKind();
    if (kind === "launchd") {
      run("launchctl", ["start", LAUNCHD_LABEL]);
    } else if (kind === "systemd") {
      run("systemctl", ["--user", "start", SYSTEMD_UNIT]);
    }
    console.log("Daemon started via service manager.");
    return;
  }
  const existing = readPid(home);
  if (existing && pidAlive(existing)) {
    console.log(`Daemon already running (pid ${existing}).`);
    return;
  }
  const pid = startBackgroundProcess(home);
  console.log(`Daemon started in background (pid ${pid}). Logs: ${getLogPath(home)}`);
}

export function stopDaemon(home: string = homedir()): void {
  if (isServiceInstalled(home)) {
    const kind = serviceKind();
    if (kind === "launchd") {
      runCapture("launchctl", ["stop", LAUNCHD_LABEL]);
    } else if (kind === "systemd") {
      runCapture("systemctl", ["--user", "stop", SYSTEMD_UNIT]);
    }
    console.log("Daemon stopped via service manager.");
    return;
  }
  const pid = readPid(home);
  if (!pid) {
    console.log("Daemon is not running (no PID file).");
    return;
  }
  if (pidAlive(pid)) {
    try {
      process.kill(pid, "SIGTERM");
      console.log(`Sent SIGTERM to daemon (pid ${pid}).`);
    } catch (err) {
      console.error(`Failed to stop daemon: ${(err as Error).message}`);
    }
  } else {
    console.log("Daemon PID is stale; cleaning up.");
  }
  rmSync(getPidPath(home), { force: true });
}

export function restartDaemon(home: string = homedir()): void {
  stopDaemon(home);
  startDaemon(home);
}

export function statusDaemon(home: string = homedir()): void {
  const kind = serviceKind();
  console.log(`Platform service manager: ${kind}`);

  if (isServiceInstalled(home)) {
    console.log(`Service installed: yes (${isServiceRunning(home) ? "running" : "stopped"})`);
  } else {
    const pid = readPid(home);
    if (pid && pidAlive(pid)) {
      console.log(`Background daemon running (pid ${pid}).`);
    } else {
      console.log("Daemon not running.");
    }
  }

  const config = configExists(home) ? loadConfig(home) : null;
  if (!config) {
    console.log("Worker: unknown (no config).");
    return;
  }
  console.log(`Worker URL: ${config.worker_url}`);
  checkWorkerOnline(config.worker_url);
}

function checkWorkerOnline(workerUrl: string): void {
  // Best-effort synchronous-looking status via runCapture(curl) fallback,
  // but prefer fetch when available (Node >= 18).
  fetch(`${workerUrl.replace(/\/$/, "")}/health`)
    .then((res) => {
      console.log(`Worker: ${res.ok ? "online" : `responded ${res.status}`}`);
    })
    .catch(() => {
      console.log("Worker: offline / unreachable");
    });
}

// ---------------------------------------------------------------------------
// Foreground + logs
// ---------------------------------------------------------------------------

export function runForeground(home: string = homedir()): void {
  requireConfig(home);
  buildDaemon();
  const entry = getDaemonEntry();
  console.log(`Running daemon in foreground: ${entry}`);
  run(process.execPath, [entry], { cwd: getRepoRoot() });
}

export function tailLogs(home: string = homedir(), lines = 200): void {
  const logPath = getLogPath(home);
  if (!existsSync(logPath)) {
    console.log(`No log file yet at ${logPath}`);
    return;
  }
  if (commandExists("tail")) {
    run("tail", ["-n", String(lines), "-f", logPath]);
  } else {
    console.log(readFileSync(logPath, "utf8"));
  }
}

// ---------------------------------------------------------------------------
// Uninstall (full)
// ---------------------------------------------------------------------------

export function uninstall(home: string = homedir(), removeConfig = false): void {
  stopDaemon(home);
  uninstallService(home);
  if (removeConfig) {
    const dir = getConfigDir(home);
    rmSync(dir, { recursive: true, force: true });
    console.log(`Removed ${dir}`);
  } else {
    console.log(`Left config in place at ${getConfigDir(home)} (use --yes to remove).`);
  }
}
